zh_cn translation
Layers-of-Railways/Railway pull request #11
Opened 2022-11-25 14:45 UTC by Catchmons

2022-11-26 13:11 UTC, iamliuzy requested changes
Good job

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"block.railways.semaphore": "壁板式信号机",
```suggestion
	"block.railways.semaphore": "壁板信号机",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.conductor_redstoning.text_2": "它同样可以在玩家注视它时拨动拉杆。",
```suggestion
	"railways.ponder.conductor_redstoning.text_2": "它同样可以在玩家注视它时拉动拉杆。",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.header": "使用壁板式信号机可视化信号状态",
```suggestion
	"railways.ponder.train_semaphore.header": "使用壁板信号机可视化信号状态",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_1": "将壁板式信号机放置在列车信号机上方的杆上",
```suggestion
	"railways.ponder.train_semaphore.text_1": "将壁板信号机放置在列车信号机上方的杆上",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_2": "壁板式信号机下方的杆可由不同材料组成",
```suggestion
	"railways.ponder.train_semaphore.text_2": "壁板信号机下方的支柱可由不同材料组成",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_3": "壁板式信号机会实时显示杆下信号机的信号状态",
```suggestion
	"railways.ponder.train_semaphore.text_3": "壁板信号机会实时显示支柱下信号机的信号状态",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_5": "...可以将第二个壁板式信号机放置在第一个的上方",
```suggestion
	"railways.ponder.train_semaphore.text_5": "...可以将第二个壁板信号机放置在第一个的上方",
```

2022-11-26 13:11 UTC, iamliuzy commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_8": "当两个壁板式信号机都放置在非黄铜信号机上时，它们会同时关闭",
```suggestion
	"railways.ponder.train_semaphore.text_8": "当两个壁式信号机都放置在非黄铜信号机上时，它们会同时关闭",
```

2022-11-27 11:20 UTC, ChuijkYahus commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"block.railways.semaphore": "壁板信号机",
```suggestion
	"block.railways.semaphore": "臂板信号机",
```

2022-11-27 11:20 UTC, ChuijkYahus commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_8": "当两个壁式信号机都放置在非黄铜信号机上时，它们会同时关闭",
```suggestion
	"railways.ponder.train_semaphore.header": "使用臂板信号机可视化信号状态",
	"railways.ponder.train_semaphore.text_1": "将臂板信号机放置在列车信号机上方的杆上",
	"railways.ponder.train_semaphore.text_2": "臂板信号机下方的支柱可由不同材料组成",
	"railways.ponder.train_semaphore.text_3": "臂板信号机会实时显示支柱下信号机的信号状态",
	"railways.ponder.train_semaphore.text_4": "如果黄铜模式信号区间有多个有效的出口路径……",
	"railways.ponder.train_semaphore.text_5": "……可以将第二个臂板信号机放置在第一个的上方",
	"railways.ponder.train_semaphore.text_6": "如果有任一可用区间被阻塞，底部的臂板信号机将会关闭",
	"railways.ponder.train_semaphore.text_7": "如果所有区间都被阻塞，顶部的臂板信号机将会关闭",
	"railways.ponder.train_semaphore.text_8": "当两个臂板信号机都放置在非黄铜信号机上时，它们会同时关闭",
```
wrong character & proper ellipsis

2022-11-27 11:20 UTC, ChuijkYahus commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.conductor_redstoning.text_3": "当玩家戴着与其颜色不一致的列车长帽时，指挥机器人不会激活红石元件。",
```suggestion
	"railways.ponder.conductor_constructing.text_1": "指挥机器人由安山机壳组成",
	"railways.ponder.conductor_redstoning.header": "借助指挥机器人远程操控红石元件",
	"railways.ponder.conductor_redstoning.text_1": "指挥机器人可以在玩家注视它时按下按钮",
	"railways.ponder.conductor_redstoning.text_2": "它同样可以在玩家注视它时拉动拉杆",
	"railways.ponder.conductor_redstoning.text_3": "当玩家戴着与其颜色不一致的列车长帽时，指挥机器人不会激活红石元件",
```
The original translation for Create has no periods in ponder lines.

2022-11-27 12:40 UTC, ChuijkYahus commented on src/generated/resources/assets/railways/lang/zh_cn.json
> +	"railways.ponder.train_semaphore.text_5": "...可以将第二个臂板信号机放置在第一个的上方",
```suggestion
	"railways.ponder.train_semaphore.text_4": "如果黄铜信号区间有多个有效的出口路径……",
	"railways.ponder.train_semaphore.text_5": "……可以将第二个臂板信号机放置在第一个的上方",
```

2022-11-29 01:09 UTC, techno-sam commented
Please move this file to `src/main/resources/assets/railways/lang/`, if you put it in src/generated, it will be deleted the next time we run datagen

2022-12-03 04:33 UTC, Catchmons commented
I think it's done right now

2022-12-03 15:37 UTC, techno-sam approved these changes
Looks good, thanks for translating!
If it isn't an inconvenience to you, please check back once in a while to see if there are missing translations.

2022-12-03 15:38 UTC, merged